/**
 * Build scripts
 */

module.exports = function(grunt) {

    // load most all grunt tasks
    require('load-grunt-tasks')(grunt);

    // Project configuration.
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        copyTargets: ['**', '!**/*~'].concat(
            // 1. Get `.distignore` file as a string
            // 2. add `!` to beginning of every line
            // 3. add `**` after a `/` occuring at the end of a line
            // 4. return as an array
            grunt.file.read('.distignore').toString().trim().replace(/^/gm, "!").replace(/\/$/gm, "/**").split("\n")
        ),

        usebanner: {
            main: {
                options: {
                    position: 'top',
                    banner: '/*! <%= pkg.name %> <%= pkg.version %> */',
                    linebreak: true
                },
                files: {
                    src: ['build/js/*.js']
                }
            }
        },

        // Remove the build directory files
        clean: {
           main: ['build/**'],
           save: ['js/index.asset.php']
        },

        // Copy the plugin into the build directory
        copy: {
            main: {
                src: '<%= copyTargets %>',
                dest: 'build/'
            },
            save: {
                src: 'build/js/index.asset.php',
                dest: 'js/index.asset.php',
                options: {
                    process: function (content) {
                        return content.replace(/^<\?php /, '<?php /*! THIS FILE IS AUTOGENERATED - DO NOT MODIFY */\n' );
                    }
                }
            }
        },

        // Generate readme.md from readme.txt
        wp_readme_to_markdown: {
            convert: {
                screenshot_url: "assets/{screenshot}.{png,gif}",
                files: {
                    'README.md': 'readme.txt'
                },
            },
        },

        // # Internationalization

        // Add text domain
        addtextdomain: {
            textdomain: '<%= pkg.name %>',
            target: {
                files: {
                    src: ['*.php', '**/*.php', '!node_modules/**', '!build/**']
                }
            }
        },

        // Generate .pot file
        makepot: {
            target: {
                options: {
                    domainPath: '/languages', // Where to save the POT file.
                    exclude: ['build'], // List of files or directories to ignore.
                    mainFile: '<%= pkg.name %>.php', // Main project file.
                    potFilename: '<%= pkg.name %>.pot', // Name of the POT file.
                    type: 'wp-plugin' // Type of project (wp-plugin or wp-theme).
                }
            }
        },

        // bump version numbers
        replace: {
            Version: {
                src: [
                    'readme.txt',
                    'readme.md',
                    '<%= pkg.name %>.php'
                ],
                overwrite: true,
                replacements: [
                    {
                        from: /Stable tag:.*$/m,
                        to: "Stable tag: <%= pkg.version %>"
                    },
                    {
                        from: /Version:.*$/m,
                        to: "Version:             <%= pkg.version %>"
                    },
                    {
                        from: /public static \$version = \'.*.'/m,
                        to: "public static $version = '<%= pkg.version %>'"
                    },
                    {
                        from: /public \$version      = \'.*.'/m,
                        to: "public $version      = '<%= pkg.version %>'"
                    }
                ]
            }
        }

    });

    // Default task(s).
    grunt.registerTask('default', [
        // 'jshint',
        // 'uglify'
    ]);

    grunt.registerTask('test', [
        // 'jshint',
        'addtextdomain'
    ]);

    grunt.registerTask('docs', [
        'wp_readme_to_markdown'
    ]);

    grunt.registerTask('build', [
        'usebanner',
        'replace',
        // 'newer:uglify',
        'makepot',
        'wp_readme_to_markdown',
    ]);

    grunt.registerTask('release', [
        'build',
        'copy'
    ])

};
